### PR TITLE
Update runtime to 5.15-23.08

### PR DESCRIPTION
**Pull request by zestygrass**
Update to the latest runtime available for KDE.

### CODE REVIEW

**Comment by zocker-160** [comment]
any specific reason to do this?

**Comment by zocker-160** [comment]
> Didn't wanted to have another runtime installed

You will probably not like this answer, but while this might be true for you, there are very likely many users out there (including me actually) where the 23.08 runtime would be additional.

I am however willing to push this to the beta branch, but on stable I don't see the point as long as 22.08 is an officially supported and updated runtime.

**Comment by zestygrass** [comment]
that's cool, I'll let you decide what is best approach here.
I'm using SyncThingy regardless.

**Comment by zocker-160** [comment]
closing in favor of #59

**Pull request closed without merging**
